# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.5.1/charts/library/common/values.schema.json
app_host: &app_host 'jellyfin.k3s.pro'
app_port: &app_port 8096

controllers:
  main:
    strategy: Recreate
    containers:
      app:
        image:
          repository: ghcr.io/hotio/prowlarr
          tag: release-10.10.5
          pullPolicy: Always

        env:
          PUID: '1000'
          PGID: '1000'
          TZ: 'America/Chicago'

        # probes:
        #   liveness: &probes
        #     enabled: true
        #     custom: true
        #     spec:
        #       httpGet:
        #         path: /health
        #         port: *app_port
        #       initialDelaySeconds: 300
        #       periodSeconds: 10
        #   readiness: *probes

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 10Gi
    globalMounts:
      - path: /config
  # movies:
  #   enabled: true
  #   type: persistentVolumeClaim
  #   existingClaim: downloads-storage
  #   globalMounts:
  #     - path: /data/movies
  #       subPath: complete/movies
  # tvshows:
  #   enabled: true
  #   type: persistentVolumeClaim
  #   existingClaim: downloads-storage
  #   globalMounts:
  #     - path: /data/tvshows
  #       subPath: complete/tv
  # youtube:
  #   enabled: true
  #   type: persistentVolumeClaim
  #   existingClaim: downloads-storage
  #   globalMounts:
  #     - path: /data/youtube
  #       subPath: youtube

service:
  app:
    controller: main
    ports:
      http:
        port: *app_port

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: 'traefik'
      cert-manager.io/cluster-issuer: 'letsencrypt'
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/name: Jellyfin
      gethomepage.dev/description: Media streaming server
      gethomepage.dev/group: Media
      gethomepage.dev/icon: jellyfin.png
      gethomepage.dev/siteMonitor: 'https://jellyfin.k3s.pro'
    className: 'traefik'
    hosts:
      - host: *app_host
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *app_host
        secretName: jellyfin-ingress-cert

defaultPodOptions:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: media
                operator: In
                values:
                  - 'true'
