# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.1.2/charts/other/app-template/values.schema.json
app_host: &app_host 'jellyfin.k3s.pro'
app_port: &app_port 8096

controllers:
  main:
    strategy: Recreate
    replicas: 1
    initContainers:
      init-dirs:
        image:
          repository: busybox
          tag: latest
          pullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - |
              mkdir -p /downloads/movies /downloads/tv /downloads/youtube /downloads/x && \
              chown -R 1000:1000 /downloads && \
              chmod -R 755 /downloads
        securityContext:
          runAsUser: 0
    containers:
      app:
        image:
          repository: ghcr.io/hotio/jellyfin
          tag: release-10.10.7
          pullPolicy: IfNotPresent

        env:
          PUID: '1000'
          PGID: '1000'
          UMASK: '002'
          TZ: 'America/Chicago'

        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: *app_port
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 5
          readiness: *probes

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 10Gi
    globalMounts:
      - path: /config

  downloads:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: downloads-storage
    globalMounts:
      - path: /downloads

service:
  app:
    controller: main
    ports:
      http:
        port: *app_port
  tailscale:
    controller: main
    type: LoadBalancer
    loadBalancerClass: tailscale
    ports:
      https:
        port: 443
        targetPort: *app_port
        protocol: TCP

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: 'traefik'
      cert-manager.io/cluster-issuer: 'letsencrypt'
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/name: Jellyfin
      gethomepage.dev/description: Media streaming server
      gethomepage.dev/group: Media
      gethomepage.dev/icon: jellyfin.png
      gethomepage.dev/siteMonitor: 'https://jellyfin.k3s.pro'
    className: 'traefik'
    hosts:
      - host: *app_host
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *app_host
        secretName: jellyfin-ingress-cert

defaultPodOptions:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: media
                operator: In
                values:
                  - 'true'
