---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-env
  namespace: linkding
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: linkding-env
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        LD_SUPERUSER_NAME: '{{ .LD_SUPERUSER_NAME }}'
        LD_SUPERUSER_PASSWORD: '{{ .LD_SUPERUSER_PASSWORD }}'
  dataFrom:
    - extract:
        key: linkding
