# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.7.0/charts/library/common/values.schema.json
app_host: &app_host 'change.k3s.pro'
app_url: &app_url 'https://change.k3s.pro'
app_port: &app_port 5000
playwright_host: &playwright_host 'playwright.k3s.pro'
playwright_port: &playwright_port 3000

controllers:
  main:
    strategy: Recreate
    replicas: 1

    containers:
      app:
        image:
          repository: ghcr.io/dgtlmoon/changedetection.io
          tag: 0.49.17
          pullPolicy: IfNotPresent

        env:
          BASE_URL: *app_url
          PLAYWRIGHT_DRIVER_URL: 'wss://playwright.k3s.pro/?stealth=1&--disable-web-security=true'

        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: *app_port
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 2
              failureThreshold: 5
          readiness: *probes

  playwright-chrome:
    strategy: Recreate
    replicas: 1

    containers:
      playwright-chrome:
        image:
          repository: browserless/chrome
          tag: latest
          pullPolicy: IfNotPresent

        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: *playwright_port
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 2
              failureThreshold: 5
          readiness: *probes

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    advancedMounts:
      main:
        app:
          - path: /datastore

service:
  app:
    controller: main
    ports:
      http:
        port: *app_port

  playwright-chrome:
    controller: playwright-chrome
    ports:
      http:
        port: *playwright_port

ingress:
  main:
    enabled: true
    annotations:
      # These annotations will configure how this deployment is shown in Homepage
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/name: ChangeDetection
      gethomepage.dev/description: Detect changes in websites
      gethomepage.dev/group: Apps
      gethomepage.dev/icon: changedetection-io.png
      gethomepage.dev/siteMonitor: *app_url

      # cert-manager
      kubernetes.io/ingress.class: 'traefik'
      cert-manager.io/cluster-issuer: 'letsencrypt'
    className: 'traefik'
    hosts:
      - host: *app_host
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *app_host
        secretName: changedetection-ingress-cert

  playwright-chrome:
    enabled: true
    annotations:
      # cert-manager
      kubernetes.io/ingress.class: 'traefik'
      cert-manager.io/cluster-issuer: 'letsencrypt'
    className: 'traefik'
    hosts:
      - host: *playwright_host
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: playwright-chrome
              port: http
    tls:
      - hosts:
          - *playwright_host
        secretName: changedetection-playwright-chrome-ingress-cert
