# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.4.0/charts/library/common/values.schema.json
host: &host 'changedetection.k3s.pro'
url: &url 'https://changedetection.k3s.pro'
app_port: &app_port 5000
playwright_port: &playwright_port 3000

controllers:
  main:
    strategy: Recreate

    containers:
      app:
        image:
          repository: ghcr.io/dgtlmoon/changedetection.io
          tag: 0.46.03
          pullPolicy: IfNotPresent

        env:
          BASE_URL: *url
          PLAYWRIGHT_DRIVER_URL: 'ws://playwright-chrome:3000/?stealth=1&--disable-web-security=true'

      playwright-chrome:
        image:
          repository: browserless/chrome
          tag: latest
          pullPolicy: IfNotPresent

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /datastore

service:
  app:
    controller: main
    ports:
      http:
        port: *app_port

  playwright-chrome:
    controller: main
    ports:
      http:
        port: *playwright_port

ingress:
  main:
    enabled: true
    annotations:
      # These annotations will configure how this deployment is shown in Homepage
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/name: ChangeDetection
      gethomepage.dev/description: Detect changes in websites
      gethomepage.dev/group: Apps
      gethomepage.dev/icon: changedetection-io.png
      gethomepage.dev/siteMonitor: 'https://changedetection.k3s.pro'

      # cert-manager
      kubernetes.io/ingress.class: 'traefik'
      cert-manager.io/cluster-issuer: 'letsencrypt'
    className: 'traefik'
    hosts:
      - host: *host
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *host
        secretName: changedetection-ingress-cert
