apiVersion: v1
kind: Service
metadata:
  labels:
    app: broker
  name: broker
  namespace: paperless

spec:
  ports:
    - name: broker
      port: 6379
      targetPort: 6379

  selector:
    app: broker
