# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
  namespace: paperless
spec:
  instances: 3
  storage:
    # https://cloudnative-pg.io/documentation/current/storage/#block-storage-considerations-ceph-longhorn
    storageClass: local-path
    size: 5Gi
