# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-external-secret
  namespace: paperless
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: paperless-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        PAPERLESS_SECRET_KEY: {{ .PAPERLESS_SECRET_KEY }}
        PAPERLESS_ADMIN_USER: {{ .PAPERLESS_ADMIN_USER }}
        PAPERLESS_ADMIN_PASSWORD: {{ .PAPERLESS_ADMIN_PASSWORD }}
  dataFrom:
    - extract:
        key: paperless


