apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: redisdata
  name: redisdata
  namespace: paperless

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 100Mi
