apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
  name: webserver
  namespace: paperless

spec:
  ports:
    - name: webserver
      port: 8000
      targetPort: 8000

  selector:
    app: webserver
