apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: webserver
  name: webserver-export
  namespace: paperless

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 100Mi

