apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: webserver
  name: webserver-data
  namespace: paperless

spec:
  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 100Mi
