apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: media
  name: webserver-media
  namespace: paperless

spec:
  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 100Mi
