[providers.age]
type = "age"
recipients = ["age137e8evn2lyhx4h39nnnkegx3gzkj792fu655mdn8p75ecalh5epssumnfp"]

[secrets]
GRAFANA_SERVICE_ACCOUNT_TOKEN = { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuLzQxNVFVdTR4VmdJNW51UkNMSWM5UjdqQkx6UDBHb1NVaG8zcHEwMm5rCkxoWGNaakpNVTNTMElaWE14MXI0VlB3N3ZuMDllcU1MTWZRNlNGQ3NOVXcKLT4gbHF9TUhwLWdyZWFzZQptb2NVTDdHTkUzM1dJL1RGMzdhSDFTMzhGWmg0d1pPekxLSEdRemN3NGlpMUsyajBCVjdWN0F1dG9Mb3M1VFp2CjUxaExOZ3VUdUhPSytkRys1UQotLS0gK3hRTlowbWdyaERJeFQ0RXg2ekdRSzg2ZG1JOTNoL3piOEtDZkVBMjZEdwpB3ZnSnOmkv8pry6WRzfhnPy46qC76Gr2FfiHAGx9yEXcZ7Y1STqhzWq/fHxCAJPTPoebejO4hMvCXz/CnJeqrj30irN2kSHyj/4r6rFY=" }
