{
 "title": "Speedtest / Overview",
 "description": "Speedtest metrics.",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "expr": "max by (job) (speedtest_download_bytes_second) / 125000",
     "legendFormat": "Download (speedtest)"
    },
    {
     "expr": "max by (job) (speedtest_upload_bytes_second) / 125000",
     "legendFormat": "Upload (speedtest)"
    },
    {
     "expr": "max by (job) (fastcom_download_bytes_second) / 125000",
     "legendFormat": "Download (fast.com)"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (job) (speedtest_ping_latency_seconds)",
     "legendFormat": "Latency"
    },
    {
     "expr": "max by (job) (speedtest_ping_jitter_seconds)",
     "legendFormat": "Jitter"
    }
   ]
  },
  {
   "title": "Packet loss",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (job) (speedtest_packet_loss_pct)",
     "legendFormat": "Packet loss"
    }
   ]
  }
 ]
}