# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.7.0/charts/library/common/values.schema.json
app_host: &app_host 'sabnzbd.k3s.pro'
app_port: &app_port 8080

controllers:
  main:
    strategy: Recreate
    replicas: 1
    initContainers:
      init-dirs:
        image:
          repository: busybox
          tag: latest
          pullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - |
            mkdir -p /downloads/complete/movies \
                     /downloads/complete/tv \
                     /downloads/complete/books \
                     /downloads/complete/audio \
                     /downloads/complete/other \
                     /downloads/complete/youtube && \
            mkdir -p /downloads/incomplete && \
            chown -R 1000:1000 /downloads && \
            chmod -R 755 /downloads
        securityContext:
          runAsUser: 0
    containers:
      app:
        nameOverride: 'sabnzbd'
        image:
          repository: ghcr.io/hotio/sabnzbd
          tag: release-4.5.1
          pullPolicy: IfNotPresent

        env:
          PUID: '1000'
          PGID: '1000'
          UMASK: '002'
          TZ: 'America/Chicago'
          SABNZBD__HOST_WHITELIST_ENTRIES: >-
            sabnzbd,
            sabnzbd.default,
            sabnzbd.default.svc,
            sabnzbd.default.svc.cluster,
            sabnzbd.default.svc.cluster.local,
            sabnzbd.k3s.pro

        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api?mode=version
                port: *app_port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 2
              failureThreshold: 5
          readiness: *probes

        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 5Gi
  exportarr:
    strategy: Recreate

    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v2.2.0
        args:
          - sabnzbd
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
            add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
        resources:
          requests:
            cpu: 15m
            memory: 50Mi
          limits:
            memory: 100Mi
        env:
          PORT: '9707'
          URL: 'https://sabnzbd.k3s.pro'
        envFrom:
          - secretRef:
              name: sabnzbd-env

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /config

  downloads:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: downloads-storage
    globalMounts:
      - path: /downloads

  tmp:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /tmp

defaultPodOptions:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: media
                operator: In
                values:
                  - 'true'

service:
  app:
    controller: main
    ports:
      http:
        port: *app_port

  exportarr:
    controller: exportarr
    ports:
      http:
        port: 9707
    labels:
      instance: 'sabnzbd'

serviceMonitor:
  exportarr:
    enabled: true
    serviceName: 'sabnzbd-exportarr'
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s
    targetLabels:
      - instance

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: 'traefik'
      cert-manager.io/cluster-issuer: 'letsencrypt'
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/name: SABnzbd
      gethomepage.dev/description: Usenet download client
      gethomepage.dev/group: Media
      gethomepage.dev/icon: sabnzbd.png
      gethomepage.dev/siteMonitor: 'https://sabnzbd.k3s.pro'
    className: 'traefik'
    hosts:
      - host: *app_host
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *app_host
        secretName: sabnzbd-ingress-cert
