# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wg-easy-env
  namespace: wg-easy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: wg-easy-env
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        # generate this value using docker run ghcr.io/wg-easy/wg-easy wgpw YOUR_PASSWORD
        PASSWORD_HASH: '{{ .PASSWORD_HASH }}'
  dataFrom:
    - extract:
        key: wg-easy
