# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.1.2/charts/other/app-template/values.schema.json
dns_port: &dns_port 53

controllers:
  main:
    strategy: RollingUpdate
    replicas: 2 # High availability

    containers:
      app:
        image:
          repository: ghcr.io/dockur/dnsmasq
          tag: 2.91
          pullPolicy: IfNotPresent

        env:
          DNS1: '10.0.1.100' # Forward to Blocky

        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - 'nslookup example.com 127.0.0.1 || exit 1'
              initialDelaySeconds: 10
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 3
          readiness: *probes

        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi

        securityContext:
          runAsUser: 0 # Run as root - dockur image needs write access to /etc/
          allowPrivilegeEscalation: false
          capabilities:
            add:
              - NET_ADMIN
            drop:
              - ALL

defaultPodOptions:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: blocky
          topologyKey: kubernetes.io/hostname

persistence:
  config:
    type: configMap
    name: tailscale-dns
    globalMounts:
      - path: /etc/dnsmasq.d/tailscale.conf
        subPath: tailscale.conf
        readOnly: true

configMaps:
  config:
    data:
      tailscale.conf: |
        # Custom entries for k3s.pro domains pointing to Tailscale IPs
        # NOTE: You'll need to update these IPs after getting your Tailscale ingress IPs

        # Example entries - update these with actual Tailscale IPs:
        # address=/jellyfin.k3s.pro/100.x.x.x
        # address=/blocky.k3s.pro/100.x.x.x
        # address=/blocky-ui.k3s.pro/100.x.x.x

        # Jellyfin Tailscale IP
        address=/jellyfin.k3s.pro/100.82.14.60

        # Wildcard for all k3s.pro subdomains (fallback)
        address=/.k3s.pro/127.0.0.1

service:
  app:
    controller: main
    type: ClusterIP
    annotations:
      tailscale.com/expose: 'true'
    ports:
      dns:
        enabled: true
        port: *dns_port
        protocol: UDP
        targetPort: 53
