# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.7.0/charts/library/common/values.schema.json
external_host: &external_host 'home.console.lol'
host: &host 'wg.k3s.pro'
url: &url 'https://wg.k3s.pro'
http_port: &http_port 51821
wireguard_port: &wireguard_port 51820
wireguard_external_port: &wireguard_external_port 31820

controllers:
  main:
    strategy: Recreate
    replicas: 1

    containers:
      app:
        image:
          repository: ghcr.io/wg-easy/wg-easy
          tag: '15'
          pullPolicy: IfNotPresent

        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
          privileged: true

        env:
          # WEBUI_HOST: *host
          WG_HOST: *external_host
          # does not change the internal port in the container, likely just used
          # for client config file generation
          WG_PORT: *wireguard_external_port
          ENABLE_PROMETHEUS_METRICS: 'true'

        envFrom:
          - secretRef:
              name: wg-easy-env

        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: *http_port
              initialDelaySeconds: 60
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /etc/wireguard

service:
  app:
    controller: main
    ports:
      http:
        port: *http_port

      wireguard-internal:
        port: *wireguard_port
        protocol: UDP
        targetPort: *wireguard_port

  wireguard:
    type: NodePort
    controller: main
    ports:
      wireguard:
        port: *wireguard_port
        protocol: UDP
        targetPort: *wireguard_port
        nodePort: *wireguard_external_port

ingress:
  main:
    enabled: true
    annotations:
      # These annotations will configure how this deployment is shown in Homepage
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/name: WireGuard
      gethomepage.dev/description: WireGuard VPN
      gethomepage.dev/group: Network
      gethomepage.dev/icon: wireguard.svg
      gethomepage.dev/siteMonitor: *url

      # cert-manager
      kubernetes.io/ingress.class: 'traefik'
      cert-manager.io/cluster-issuer: 'letsencrypt'
    className: 'traefik'
    hosts:
      - host: *host
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *host
        secretName: wg-easy-ingress-cert
