# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: freshrss-env
  namespace: freshrss
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: freshrss-env
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        FRESHRSS_USER: '{{ .FRESHRSS_USER }}'
  dataFrom:
    - extract:
        key: freshrss
