# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-admin
  namespace: gitea
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: gitea-admin
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        username: '{{ .username }}'
        password: '{{ .password }}'
        email: '{{ .email }}'
  dataFrom:
    - extract:
        key: gitea
