ingress:
  enabled: true
  className: traefik
  annotations:
    kubernetes.io/ingress.class: 'traefik'
    cert-manager.io/cluster-issuer: 'letsencrypt'
  hosts:
    - host: git.k3s.pro
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: gitea-ingress-cert
      hosts:
        - 'git.k3s.pro'

replicaCount: 2

persistence:
  enabled: true
  size: 3Gi
  subPath: gitea

postgresql-ha:
  enabled: true
  service:
    ports:
      postgresql: 5432
  primary:
    persistence:
      size: 10Gi

gitea:
  admin:
    existingSecret: gitea-admin
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
