# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-postgresql-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: grafana-postgresql-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        grafana_readonly_password: '{{ .grafana_readonly_password }}'
  dataFrom:
    - extract:
        key: blocky_grafana_readonly
        metadataPolicy: None
        decodingStrategy: None
        conversionStrategy: Default
