# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        grafana_username: '{{ .grafana_username }}'
        grafana_password: '{{ .grafana_password }}'
  dataFrom:
    - extract:
        key: monitoring
