# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
  namespace: external-secrets
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.onepassword-connect.svc.cluster.local:8080
      vaults:
        K3s.Pro: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-connect-access-token
            key: token
            namespace: external-secrets
