# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: op-connect-access-token-external-secret
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: op-connect-access-token
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      # prettier-ignore
      data:
        token: '{{ .op_connect_access_token }}'
  dataFrom:
    - extract:
        key: external-secrets
        metadataPolicy: None
        decodingStrategy: None
        conversionStrategy: Default
        nullBytePolicy: Ignore
