# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: op-connect-access-token-external-secret
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: op-connect-access-token
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        token: '{{ .op-connect-access-token }}'
  dataFrom:
    - extract:
        key: external-secrets
