# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex-env
  namespace: plex
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: plex-env
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        # Get your claim token from https://www.plex.tv/claim/
        PLEX_CLAIM: '{{ .PLEX_CLAIM }}'
  dataFrom:
    - extract:
        key: plex
