# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-env
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: forgejo-env
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        FORGEJO__security__SECRET_KEY: '{{ .SECRET_KEY }}'
  dataFrom:
    - extract:
        key: forgejo
        metadataPolicy: None
        decodingStrategy: None
        conversionStrategy: Default
