# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-env
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: forgejo-runner-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        FORGEJO_RUNNER_REGISTRATION_TOKEN: '{{ .FORGEJO_RUNNER_REGISTRATION_TOKEN }}'
  dataFrom:
    - extract:
        key: forgejo-runner
        metadataPolicy: None
        decodingStrategy: None
        conversionStrategy: Default
