apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-media-storage
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: '1'
  nodeSelector: 'media'

