apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  labels:
    io.kompose.service: uptime-kuma
  name: uptime-kuma
  namespace: uptime

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 200Mi
