# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun-env
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: gluetun-env
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        # ProtonVPN Configuration
        # see https://account.proton.me/u/0/vpn/WireGuard
        # and https://protonvpn.com/support/wireguard-configurations/
        WIREGUARD_PRIVATE_KEY: '{{ .WIREGUARD_PRIVATE_KEY }}'
  dataFrom:
    - extract:
        key: gluetun
        metadataPolicy: None
        decodingStrategy: None
        conversionStrategy: Default
