# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bazarr-env
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: bazarr-env
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        APIKEY: '{{ .APIKEY }}'
  dataFrom:
    - extract:
        key: bazarr
        metadataPolicy: None
        decodingStrategy: None
        conversionStrategy: Default
