# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.7.0/charts/library/common/values.schema.json
app_host: &app_host 'bazarr.k3s.pro'
app_url: &app_url 'https://bazarr.k3s.pro'
app_port: &app_port 6767

controllers:
  main:
    strategy: Recreate
    replicas: 1
    containers:
      app:
        nameOverride: bazarr
        image:
          repository: ghcr.io/hotio/bazarr
          tag: release-1.5.1
          pullPolicy: IfNotPresent

        env:
          PUID: '1000'
          PGID: '1000'
          UMASK: '002'
          TZ: 'America/Chicago'

        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: *app_port
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 2
              failureThreshold: 5
          readiness: *probes
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

  exportarr:
    strategy: Recreate

    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v2.2.0
        args:
          - sonarr
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
            add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
        resources:
          requests:
            cpu: 15m
            memory: 50Mi
          limits:
            memory: 100Mi
        env:
          PORT: '9707'
          URL: 'https://bazarr.k3s.pro'
        envFrom:
          - secretRef:
              name: bazarr-env

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 200Mi
    globalMounts:
      - path: /config

  downloads:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: downloads-storage
    globalMounts:
      - path: /downloads

service:
  app:
    controller: main
    ports:
      http:
        port: *app_port

  exportarr:
    controller: exportarr
    ports:
      http:
        port: 9707
    labels:
      instance: 'bazarr'

serviceMonitor:
  exportarr:
    enabled: true
    serviceName: 'bazarr-exportarr'
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s
    targetLabels:
      - instance

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: 'traefik'
      cert-manager.io/cluster-issuer: 'letsencrypt'
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/name: bazarr
      gethomepage.dev/description: Subtitle Downloader
      gethomepage.dev/group: Media
      gethomepage.dev/icon: bazarr.png
      gethomepage.dev/siteMonitor: *app_url
    className: 'traefik'
    hosts:
      - host: *app_host
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *app_host
        secretName: bazarr-ingress-cert

defaultPodOptions:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: media
                operator: In
                values:
                  - 'true'
