# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-smtp
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nextcloud-smtp
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        username: '{{ .username }}'
        password: '{{ .password }}'
  dataFrom:
    - extract:
        key: nextcloud-smtp
        metadataPolicy: None
        decodingStrategy: None
        conversionStrategy: Default
