# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.4.0/charts/library/common/values.schema.json
app_host: &app_host 'sonarr.k3s.pro'
app_port: &app_port 8989

controllers:
  main:
    strategy: Recreate
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/sonarr
          tag: latest
          pullPolicy: IfNotPresent

        env:
          PUID: '1000'
          PGID: '1000'
          TZ: 'America/Chicago'

        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: *app_port
              initialDelaySeconds: 60
              periodSeconds: 10
          readiness: *probes
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 200Mi
    globalMounts:
      - path: /config
  tv:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: downloads-pvc
    globalMounts:
      - path: /tv
        subPath: complete/tv
  downloads:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: downloads-pvc
    globalMounts:
      - path: /downloads
        subPath: complete

service:
  app:
    controller: main
    ports:
      http:
        port: *app_port

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: 'traefik'
      cert-manager.io/cluster-issuer: 'letsencrypt'
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/name: Sonarr
      gethomepage.dev/description: TV show collection manager
      gethomepage.dev/group: Media
      gethomepage.dev/icon: sonarr.png
      gethomepage.dev/siteMonitor: 'https://sonarr.k3s.pro'
    className: 'traefik'
    hosts:
      - host: *app_host
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *app_host
        secretName: sonarr-ingress-cert

