# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.1.2/charts/other/app-template/values.schema.json
app_host: &app_host 'sonarr.k3s.pro'
app_port: &app_port 8989

controllers:
  main:
    strategy: Recreate
    replicas: 1
    containers:
      app:
        nameOverride: 'sonarr'
        image:
          repository: ghcr.io/hotio/sonarr
          tag: release-4.0.14.2939
          pullPolicy: IfNotPresent

        env:
          PUID: '1000'
          PGID: '1000'
          UMASK: '002'
          TZ: 'America/Chicago'

        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: *app_port
              initialDelaySeconds: 60
              periodSeconds: 10
          readiness: *probes
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
  exportarr:
    strategy: Recreate

    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v2.2.0
        args:
          - sonarr
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
            add: ['CHOWN', 'FOWNER', 'SETGID', 'SETUID']
        resources:
          requests:
            cpu: 15m
            memory: 50Mi
          limits:
            memory: 100Mi
        env:
          PORT: '9707'
          URL: 'https://sonarr.k3s.pro'
        envFrom:
          - secretRef:
              name: sonarr-env

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    globalMounts:
      - path: /config

  downloads:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: downloads-storage
    globalMounts:
      - path: /downloads

  nas:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: nas-media
    globalMounts:
      - path: /media
        subPath: media

service:
  app:
    controller: main
    ports:
      http:
        port: *app_port

  exportarr:
    controller: exportarr
    ports:
      http:
        port: 9707
    labels:
      instance: 'sonarr'

serviceMonitor:
  exportarr:
    enabled: true
    serviceName: 'sonarr-exportarr'
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s
    targetLabels:
      - instance

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: 'traefik'
      cert-manager.io/cluster-issuer: 'letsencrypt'
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/name: Sonarr
      gethomepage.dev/description: TV show collection manager
      gethomepage.dev/group: Media
      gethomepage.dev/icon: sonarr.png
      gethomepage.dev/siteMonitor: 'https://sonarr.k3s.pro'
    className: 'traefik'
    hosts:
      - host: *app_host
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *app_host
        secretName: sonarr-ingress-cert

defaultPodOptions:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: media
                operator: In
                values:
                  - 'true'
