# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.5.1/charts/library/common/values.schema.json
url: &url 'https://browsarr.k3s.pro'
app_host: &app_host 'browsarr.k3s.pro'
app_port: &app_port 8080

controllers:
  main:
    strategy: Recreate
    containers:
      app:
        image:
          repository: hurlenko/filebrowser
          tag: v2.32.0
          pullPolicy: IfNotPresent

        securityContext:
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000

        env:
          PUID: '1000'
          PGID: '1000'
          UMASK: '002'
          TZ: 'America/Chicago'

        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: *app_port
              initialDelaySeconds: 60
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

persistence:
  filebrowser-config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 100Mi
    globalMounts:
      - path: /config

  downloads:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: downloads-storage
    globalMounts:
      - path: /data

service:
  app:
    controller: main
    ports:
      http:
        port: *app_port

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: 'traefik'
      cert-manager.io/cluster-issuer: 'letsencrypt'
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/name: browsarr
      gethomepage.dev/description: File Browser
      gethomepage.dev/group: Media
      gethomepage.dev/icon: filebrowser.png
      gethomepage.dev/siteMonitor: *url
    className: 'traefik'
    hosts:
      - host: *app_host
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *app_host
        secretName: browsarr-ingress-cert

defaultPodOptions:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: media
                operator: In
                values:
                  - 'true'
