# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications
  namespace: argo-cd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        telegram_token: '{{ .telegram_token }}'
  dataFrom:
    - extract:
        key: argo-cd
        metadataPolicy: None
        decodingStrategy: None
        conversionStrategy: Default
