# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argo-cd-service-monitor
  namespace: argo-cd
spec:
  selector:
    matchLabels:
      'app.kubernetes.io/name': 'argocd-server'
  endpoints:
    - port: metrics
