# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tsidp-env
  namespace: tsidp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: tsidp-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        TS_AUTHKEY: '{{ .TS_AUTHKEY }}'
  dataFrom:
    - extract:
        key: tsidp
        metadataPolicy: None
        decodingStrategy: None
        conversionStrategy: Default
