# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: livebook-env
  namespace: livebook
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: livebook-env
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        LIVEBOOK_PASSWORD: '{{ .LIVEBOOK_PASSWORD }}'
        LIVEBOOK_SECRET_KEY_BASE: '{{ .LIVEBOOK_SECRET_KEY_BASE }}'
  dataFrom:
    - extract:
        key: livebook
