# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/1de95b7e9cb737ba46b14fa5a033fee2e47d90a3/metallb.io/ipaddresspool_v1beta1.json
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: livebook
  namespace: metallb-system
spec:
  addresses:
    - 10.0.1.240/32
  serviceAllocation:
    namespaces:
      - livebook
    serviceSelectors:
      - matchLabels:
          metallb.k3s.pro/address-pool: livebook
