# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.4.0/charts/library/common/values.schema.json
controllers:
  main:
    # not high availability because it's using SQLite (but I can spin up a
    # postgres db - it supports that)
    strategy: Recreate

    containers:
      app:
        image:
          repository: freshrss/freshrss
          tag: 1.24.2
          pullPolicy: IfNotPresent

        env:
          # See https://github.com/FreshRSS/FreshRSS/tree/edge/Docker#environment-variables
          # And https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/example.env
          TZ: America/Chicago
          BASE_URL: https://rss.k3s.pro

        envFrom:
          - secretRef:
              name: freshrss-env

        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: &port 80
              initialDelaySeconds: 120
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    globalMounts:
      - path: /var/www/FreshRSS/data

  extensions:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /var/www/FreshRSS/extensions

service:
  app:
    controller: main
    ports:
      http:
        port: *port

ingress:
  main:
    enabled: true
    annotations:
      # These annotations will configure how this deployment is shown in Homepage
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/name: FreshRSS
      gethomepage.dev/description: RSS Feed Aggregator
      gethomepage.dev/group: Apps
      gethomepage.dev/icon: freshrss.svg
      gethomepage.dev/siteMonitor: 'https://rss.k3s.pro'

      # cert-manager
      kubernetes.io/ingress.class: 'traefik'
      cert-manager.io/cluster-issuer: 'letsencrypt'
    className: 'traefik'
    hosts:
      - host: &host 'rss.k3s.pro'
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *host
        secretName: freshrss-ingress-cert
