apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  labels:
    io.kompose.service: memos-claim0
  name: memos-claim0
  namespace: memos

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
