apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.telegram: |
    token: $telegram_token

  # Context holds list of variables that can be referenced in templates
  context: |
    argocdUrl: https://argocd.k3s.pro/
