# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-notifications
  namespace: argo-cd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        telegram-token: '{{ .telegram-token }}'
  dataFrom:
    - extract:
        key: argo-cd
