apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-storage
  namespace: media
spec:
  accessModes:
    - ReadWriteMany # Allows multiple pods to read/write
  resources:
    requests:
      storage: 300Gi
  storageClassName: longhorn-media-storage
