# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-storage
  namespace: media
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/weekly-filesystem-trim: enabled
spec:
  accessModes:
    - ReadWriteMany # Allows multiple pods to read/write
  resources:
    requests:
      # max is disk size - 25% (https://longhorn.io/docs/archives/1.3.2/references/settings/#storage-minimal-available-percentage)
      # for 500GB it's 375GB, but better make it a little lower to be safe.
      storage: 300Gi
  storageClassName: longhorn-media-storage
