apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-storage
  namespace: media
spec:
  accessModes:
    - ReadWriteMany # Allows multiple pods to read/write
  resources:
    requests:
      # max is disk size - 25% (https://longhorn.io/docs/archives/1.3.2/references/settings/#storage-minimal-available-percentage)
      # for 500GB it's 375GB, but better make it a little lower to be safe.
      storage: 300Gi
  storageClassName: longhorn-media-storage
