# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/storageclass-storage-v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-media-storage
provisioner: driver.longhorn.io
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  fromBackup: ''
  fsType: 'ext4'
  dataLocality: 'strict-local'
  disableRevisionCounter: 'true'
  unmapMarkSnapChainRemoved: ignored
  numberOfReplicas: '1'
  nodeSelector: 'media'
  diskSelector: 'media'
