# yaml-language-server: $schema=https://deedee-ops.github.io/schemas/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-cd

  sources:
    - path: argo-cd/templates
      repoURL: 'https://github.com/dkarter/k3s-cluster-apps.git'
      targetRevision: HEAD

    - repoURL: 'https://github.com/dkarter/k3s-cluster-apps.git'
      targetRevision: HEAD
      ref: values

    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 7.6.4
      helm:
        releaseName: argo-cd
        valueFiles:
          - $values/argo-cd/values.yml

  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
