# yaml-language-server: $schema=https://deedee-ops.github.io/schemas/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homepage

  sources:
    - path: homepage
      repoURL: 'https://github.com/dkarter/k3s-cluster-apps.git'
      targetRevision: HEAD

    - chart: homepage
      repoURL: https://jameswynn.github.io/helm-charts
      targetRevision: 1.2.3
      helm:
        releaseName: homepage
        valuesObject:
          image:
            repository: ghcr.io/gethomepage/homepage
            tag: v0.8.4

          # Enable RBAC. RBAC is necessary to use Kubernetes integration
          enableRbac: true

          serviceAccount:
            # Specify a different service account name
            name: homepage
            # Create service account. Needed when RBAC is enabled.
            create: true

          config:
            # To use an existing ConfigMap uncomment this line and specify the name
            # useExistingConfigMap: existing-homepage-configmap
            bookmarks:
              - Developer:
                  - Github:
                      - abbr: GH
                        href: https://github.com/

                  - HackerNews:
                      - abbr: HN
                        href: https://news.ycombinator.com/

            services:
              - Portainer Servers:
                  - Grafana:
                      icon: grafana.svg
                      href: https://monitor.console.lol
                      description: PiSrv Grafana (includes Internet Speed)

                  - Adguard:
                      icon: adguard-home.svg
                      href: https://adguard2.console.lol
                      description: DNS Ad Blocker

                  - Portainer:
                      icon: portainer.svg
                      href: https://portainer.console.lol
                      description: Manage docker container based apps

                  # - Libreddit:
                  #     icon: libreddit.svg
                  #     href: https://reddit.console.lol
                  #     description: A private Reddit client

              - K3s.Pro Infra:
                  - Longhorn:
                      icon: longhorn.svg
                      href: https://longhorn.k3s.pro
                      description: Manage Longhorn Distributed Storage

                  - Uptime Kuma:
                      icon: uptime-kuma.svg
                      href: https://uptime.k3s.pro
                      description: Monitor Uptime

            widgets:
              - kubernetes:
                  cluster:
                    show: true
                    cpu: true
                    memory: true
                    showLabel: true
                    label: 'cluster'
                  nodes:
                    show: true
                    cpu: true
                    memory: true
                    showLabel: true

              - longhorn:
                  # Show the expanded view
                  expanded: true
                  # Shows a node representing the aggregate values
                  total: true
                  # Shows the node names as labels
                  labels: true
                  # Show the nodes
                  nodes: true

              - grafana:
                  type: grafana
                  url: https://grafana.k3s.pro
                  username: admin
                  password: '{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}'

            settings:
              providers:
                longhorn:
                  url: https://longhorn.k3s.pro

            kubernetes:
              mode: cluster

          ingress:
            main:
              enabled: true
              labels:
                # This label will enable discover of this deployment in Homepage
                gethomepage.dev/enabled: 'true'
              annotations:
                # These annotations will configure how this deployment is shown in Homepage
                gethomepage.dev/name: 'Homepage'
                gethomepage.dev/description: 'A modern, secure, highly customizable application dashboard.'
                gethomepage.dev/group: 'A New Group'
                gethomepage.dev/icon: 'homepage.png'
                # cert-manager
                cert-manager.io/cluster-issuer: 'letsencrypt'
              ingressClassName: 'traefik'
              hosts:
                - host: &host 'home.k3s.pro'
                  paths:
                    - path: /
                      pathType: Prefix
              tls:
                - hosts:
                    - *host
                  secretName: homepage-ingress-cert

          envFrom:
            - secretRef:
                name: homepage-env

  project: default

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
