# yaml-language-server: $schema=https://deedee-ops.github.io/schemas/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homepage

  sources:
    - repoURL: 'https://github.com/dkarter/k3s-cluster-apps.git'
      targetRevision: HEAD
      ref: repo

    - chart: homepage
      repoURL: 'https://github.com/dkarter/k3s-cluster-apps.git'
      path: homepage
      targetRevision: HEAD
      helm:
        releaseName: homepage
        valueFiles:
          - $repo/homepage/values.yml

  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
