# yaml-language-server: $schema=https://deedee-ops.github.io/schemas/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homepage

  sources:
    - chart: homepage
      repoURL: https://jameswynn.github.io/helm-charts
      targetRevision: 1.2.3
      helm:
        releaseName: homepage
        valuesObject:
          image:
            repository: ghcr.io/gethomepage/homepage
            tag: v0.8.4

          # Enable RBAC. RBAC is necessary to use Kubernetes integration
          enableRbac: true

          serviceAccount:
            # Specify a different service account name
            name: homepage
            # Create service account. Needed when RBAC is enabled.
            create: true

          config:
            # To use an existing ConfigMap uncomment this line and specify the name
            # useExistingConfigMap: existing-homepage-configmap
            bookmarks:
              - Developer:
                  - Github:
                      - abbr: GH
                        href: https://github.com/
            services:
              - Portainer Servers:
                  - Heimdall:
                      href: https://srv.console.lol
                      description: Heimdall

                  - Monitor:
                      href: https://monitor.console.lol
                      description: Grafana dashboard monitoring internet speed, pi-srv, pi-srv2

                  - Adguard:
                      href: https://adguard2.console.lol
                      description: DNS Ad Blocker

              - My Second Group:
                  - My Second Service:
                      href: http://localhost/
                      description: Homepage is the best

              - My Third Group:
                  - My Third Service:
                      href: http://localhost/
                      description: Homepage is 😎
            widgets:
              - resources:
                  # change backend to 'kubernetes' to use Kubernetes integration. Requires RBAC.
                  backend: kubernetes
                  expanded: true
                  cpu: true
                  memory: true

              - search:
                  provider: custom
                  focus: true
                  url: https://kagi.com/search?q=
                  target: _blank

              - kubernetes:
                  cluster:
                    show: true
                    cpu: true
                    memory: true
                    showLabel: true
                    label: 'cluster'
                  nodes:
                    show: true
                    cpu: true
                    memory: true
                    showLabel: true

              - longhorn:
                  # Show the expanded view
                  expanded: true
                  # Shows a node representing the aggregate values
                  total: true
                  # Shows the node names as labels
                  labels: true
                  # Show the nodes
                  nodes: true

            kubernetes:
              mode: cluster

          ingress:
            main:
              enabled: true
              labels:
                # This label will enable discover of this deployment in Homepage
                gethomepage.dev/enabled: 'true'
              annotations:
                # These annotations will configure how this deployment is shown in Homepage
                gethomepage.dev/name: 'Homepage'
                gethomepage.dev/description: 'A modern, secure, highly customizable application dashboard.'
                gethomepage.dev/group: 'A New Group'
                gethomepage.dev/icon: 'homepage.png'
                # cert-manager
                cert-manager.io/cluster-issuer: 'letsencrypt'
              ingressClassName: 'traefik'
              hosts:
                - host: &host 'home.k3s.pro'
                  paths:
                    - path: /
                      pathType: Prefix
              tls:
                - hosts:
                    - *host
                  secretName: homepage-ingress-cert

  project: default

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
