# yaml-language-server: $schema=https://deedee-ops.github.io/schemas/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring

  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 56.0.1
      helm:
        releaseName: monitoring
        valuesObject:
          additionalServiceMonitors:
            - name: external-secrets
              namespace: vault
              selector:
                matchLabels:
                  app.kubernetes.io/name: external-secrets
              namespaceSelector:
                matchNames:
                  - vault
              endpoints:
                - port: prometheus

          alertmanager:
            ingress:
              enabled: true
              ingressClassName: traefik
              annotations:
                kubernetes.io/ingress.class: 'traefik'
                cert-manager.io/cluster-issuer: 'letsencrypt'
              hosts:
                - 'alertmanager.k3s.pro'
              paths:
                - /
              pathType: Prefix
              tls:
                - secretName: alertmanager-ingress-cert
                  hosts:
                    - 'alertmanager.k3s.pro'

          grafana:
            ingress:
              enabled: true
              ingressClassName: traefik
              annotations:
                kubernetes.io/ingress.class: 'traefik'
                cert-manager.io/cluster-issuer: 'letsencrypt'
                gethomepage.dev/enabled: 'true'
                gethomepage.dev/description: Dashboards and alerts
                gethomepage.dev/group: System
                gethomepage.dev/icon: grafana.png
                gethomepage.dev/name: Grafana
                gethomepage.dev/ping: 'https://grafana.k3s.pro/api/health'
                gethomepage.dev/widget.type: 'grafana'
                gethomepage.dev/widget.url: 'https://grafana.k3s.pro'
                gethomepage.dev/widget.username: 'admin'
                gethomepage.dev/widget.password: '{{`{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}`}}'
              hosts:
                - 'grafana.k3s.pro'
              paths:
                - /
              pathType: Prefix
              tls:
                - secretName: grafana-ingress-cert
                  hosts:
                    - 'grafana.k3s.pro'

  project: default

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
