# yaml-language-server: $schema=https://deedee-ops.github.io/schemas/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-apps
spec:
  destination:
    name: ''
    namespace: argo-cd
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/media
    repoURL: 'https://github.com/dkarter/k3s-cluster-apps.git'
    targetRevision: HEAD
    directory:
      recurse: true
      exclude: '*/templates/*'
  project: default
  syncPolicy:
    automated:
      selfHeal: true
