apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-apps
spec:
  destination:
    name: ''
    namespace: argo-cd
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/media
    repoURL: 'https://github.com/dkarter/k3s-cluster-apps.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      selfHeal: true 