# yaml-language-server: $schema=https://deedee-ops.github.io/schemas/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memos
spec:
  destination:
    name: ''
    namespace: memos
    server: 'https://kubernetes.default.svc'
  source:
    path: memos
    repoURL: 'https://github.com/dkarter/k3s-cluster-apps.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
