# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring

  sources:
    - repoURL: 'https://github.com/dkarter/k3s-cluster-apps.git'
      targetRevision: HEAD
      ref: values

    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 79.12.0
      helm:
        releaseName: monitoring
        valueFiles:
          - $values/monitoring/values.yml

  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
