apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speedtest-exporter
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: 4.6.2
      helm:
        valueFiles:
          - $values/speedtest-exporter/values.yml

    - repoURL: https://github.com/dkarter/k3s-cluster-apps.git
      targetRevision: HEAD
      ref: values

  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
