# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.1.2/charts/other/app-template/values.schema.json
app_host: &app_host 'radarr.k3s.pro'
app_port: &app_port 7878

controllers:
  main:
    strategy: Recreate
    replicas: 1
    containers:
      app:
        image:
          repository: ghcr.io/hotio/radarr
          tag: release-5.28.0.10274
          pullPolicy: IfNotPresent

        env:
          PUID: '1000'
          PGID: '1000'
          UMASK: '002'
          TZ: 'America/Chicago'

        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: *app_port
              initialDelaySeconds: 20
              periodSeconds: 10
              failureThreshold: 5
          readiness: *probes
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 200Mi
    globalMounts:
      - path: /config

  downloads:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: downloads-storage
    globalMounts:
      - path: /downloads

  nas:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: smb-nas-media
    globalMounts:
      - path: /media
        subPath: media

service:
  app:
    controller: main
    ports:
      http:
        port: *app_port

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: 'traefik'
      cert-manager.io/cluster-issuer: 'letsencrypt'
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/name: Radarr
      gethomepage.dev/description: Movie collection manager
      gethomepage.dev/group: Media
      gethomepage.dev/icon: radarr.png
      gethomepage.dev/siteMonitor: 'https://radarr.k3s.pro'
    className: 'traefik'
    hosts:
      - host: *app_host
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *app_host
        secretName: radarr-ingress-cert

defaultPodOptions:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: media
                operator: In
                values:
                  - 'true'
