app_host: &app_host 'radarr.k3s.pro'
app_port: &app_port 7878

controllers:
  main:
    strategy: Recreate
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/radarr
          tag: latest
          pullPolicy: IfNotPresent
        
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "America/Chicago"
        
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: *app_port
              initialDelaySeconds: 60
              periodSeconds: 10
          readiness: *probes
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    mountPath: /config
  movies:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: downloads-pvc
    mountPath: /movies
    subPath: complete/movies
  downloads:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: downloads-pvc
    mountPath: /downloads
    subPath: complete

service:
  main:
    ports:
      http:
        port: *app_port

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: 'traefik'
      cert-manager.io/cluster-issuer: 'letsencrypt'
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/name: Radarr
      gethomepage.dev/description: Movie collection manager
      gethomepage.dev/group: Media
      gethomepage.dev/icon: radarr.png
      gethomepage.dev/siteMonitor: 'https://radarr.k3s.pro'
    className: 'traefik'
    hosts:
      - host: *app_host
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - *app_host
        secretName: radarr-ingress-cert 