---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-env
  namespace: homepage
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: homepage-env
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        HOMEPAGE_VAR_GRAFANA_PASSWORD: '{{ .HOMEPAGE_VAR_GRAFANA_PASSWORD }}'
        HOMEPAGE_VAR_AGH_PASSWORD: '{{ .HOMEPAGE_VAR_AGH_PASSWORD }}'
        HOMEPAGE_VAR_PAPERLESS_TOKEN: '{{ .HOMEPAGE_VAR_PAPERLESS_TOKEN }}'
        HOMEPAGE_VAR_FRESHRSS_USERNAME: '{{ .HOMEPAGE_VAR_FRESHRSS_USERNAME }}'
        HOMEPAGE_VAR_FRESHRSS_PASSWORD: '{{ .HOMEPAGE_VAR_FRESHRSS_PASSWORD }}'
  dataFrom:
    - extract:
        key: homepage
