# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: adguard-exporter-env
  namespace: adguard
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: adguard-exporter-env
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        ADGUARD_USERNAMES: '{{ .ADGUARD_USERNAMES }}'
        ADGUARD_PASSWORDS: '{{ .ADGUARD_PASSWORDS }}'
  dataFrom:
    - extract:
        key: adguard-exporter
        metadataPolicy: None
        decodingStrategy: None
        conversionStrategy: Default
