# yaml-language-server: $schema=https://deedee-ops.github.io/schemas/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media

  sources:
    - repoURL: 'https://github.com/dkarter/k3s-cluster-apps.git'
      targetRevision: HEAD
      ref: values

    - chart: app-template
      repoURL: https://bjw-s.github.io/helm-charts
      targetRevision: 3.5.1
      helm:
        releaseName: prowlarr
        valueFiles:
          - $values/apps/media/prowlarr/values.yml

  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

