# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lets-encrypt-issuer-email-external-secret
  namespace: cert-manager
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: letsencrypt-issuer-email
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        email: '{{ .email }}'
  dataFrom:
    - extract:
        key: letsencrypt
