# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: digitalocean-dns
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: digitalocean-dns
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        access-token: '{{ .access_token }}'
  dataFrom:
    - extract:
        key: digitalocean-dns
        metadataPolicy: None
        decodingStrategy: None
        conversionStrategy: Default
