# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component

resources:
  - 'letsencrypt-cluster-issuer.yml'

replacements:
  - source:
      kind: Secret
      name: letsencrypt-issuer-email
      namespace: cert-manager
      fieldPath: 'data.email'
    targets:
      - select:
          namespace: cert-manager
          name: letsencrypt-2
          kind: ClusterIssuer
        fieldPaths:
          - 'spec.acme.email'
        options:
          create: true
