# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: blocky-db
  namespace: blocky
spec:
  instances: 1

  imageName: ghcr.io/clevyr/cloudnativepg-timescale:17-ts2

  postgresql:
    shared_preload_libraries:
      - timescaledb

  bootstrap:
    initdb:
      database: app
      owner: app
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS timescaledb VERSION '2.19.3';

  storage:
    # https://cloudnative-pg.io/documentation/current/storage/#block-storage-considerations-ceph-longhorn
    storageClass: local-path
    size: 2Gi

  monitoring:
    enabled: true
