apiVersion: v1
kind: Service
metadata:
  name: blocky-metallb
  namespace: blocky
  labels:
    app.kubernetes.io/instance: blocky
    app.kubernetes.io/name: blocky
    metallb.k3s.pro/address-pool: blocky
spec:
  type: LoadBalancer
  loadBalancerClass: metallb.io/load-balancer
  loadBalancerIP: 10.0.1.200
  externalTrafficPolicy: Local
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: http
      port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: blocky
    app.kubernetes.io/name: blocky
